services:
  - type: web
    name: pause-protect-backend
    env: node
    plan: standard
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BASE_URL
        sync: false
    envVarGroups:
      - name: firebase
      - name: api-keys
      - name: database
